import { News } from './app/models/news';

export const NEWS: News[] = [
    {
        imageUrl: "../../assets/newsPictures/starwarsNews.jpg",
        title: "Star Wars: The Rise of Skywalker Box Office Nears $1 Billion",
        shortDesc: "Star Wars: The Rise of Skywalker is poised to cross $1 billion worldwide soon, but its gross still trails that of The Last Jedi. While it remains...",
        longDesc: "Star Wars: The Rise of Skywalker is poised to cross $1 billion worldwide soon, but its gross still trails that of The Last Jedi. While it remains a strong accomplishment, earning $1 billion globally is far more common these days that it was just a decade ago. At the turn of the 2010s, only seven movies in history made that much, and now - with Frozen II recently reaching that mark - the number has risen all the way up to 45. At this point, if a major studio tentpole doesn't hit $1 billion during its run, it's considered a disappointment. Fortunately for Disney, they seem to have no problem selling that many tickets. The Mouse House's renaissance of the Star Wars franchise certainly contributed to the sizable uptick in $1 billion films. To date, three of them have grossed that much, with 2018's Solo: A Star Wars Story the lone outlier. Though The Rise of Skywalker posted the lowest opening weekend of the sequel trilogy, it's still found a great deal of commercial success, being the #1 movie in the world for the past two weeks. Many expected The Rise of Skywalker to be another $1 billion earner for Disney, and it's well on its way to doing just that. Per The Wrap, The Rise of Skywalker is expected to surpass $900 million worldwide this weekend, meaning it's only a matter of time before it hits $1 billion. However, The Rise of Skywalker is more than likely going to finish with a total below The Last Jedi's $1.3 billion, so the trilogy finale's box office performance is something of a mixed bag."
    },
    {
        imageUrl: "../../assets/newsPictures/jokerNews.jpg",
        title: "Joker Breaks Comic Book Movie Golden Globes Record",
        shortDesc: "At the 2020 Golden Globes Awards, Todd Phillips’ Joker broke comic book movie records. Ever since the release of Joker back in October, the...",
        longDesc: "At the 2020 Golden Globes Awards, Todd Phillips’ Joker broke comic book movie records. Ever since the release of Joker back in October, the film has been the talk of the town for one reason or another, whether it’s Joaquin Phoenix’s incredible portrayal of Batman’s arch-nemesis, the film becoming the most profitable comic book movie of all time with an over $1 billion worldwide gross, or even the struggle Phillips faced getting Warner Bros. to make the film. In more ways than one, Joker has been one of the most debated and talked about films in years. Written by director Phillips and Scott Silver, Joker tells the story of Arthur Fleck (Phoenix), who suffers from an illness where he cannot control his laughter. Slowly, due to Arthur’s mental state and the uncaring nature of people in Gotham, Arthur morphs into the DC supervillain we all know as The Joker. The storytelling is almost an homage to Martin Scorsese’s legendary films like Taxi Driver and The King of Comedy. It’s gritty, raw, and it has a deeper meaning than most comic book tales. Despite critics having different opinions on Joker due to some believing it promotes violence, few could deny the artistic brilliance of the film, and Phoenix’s remarkable portrayal that has led many to believe he is a shoo-in for an Oscar. Although there’s still time for the Oscars, Joker continued its habit of becoming the talk of the town by setting a new record at the Golden Globes. At the Golden Globes this past Sunday, Joker was nominated for a total of four awards, Best Motion Picture - Drama, Best Director – Motion Picture, Best Performance by an Actor in a Motion Picture - Drama, and Best Original Score – Motion Picture. The film walked out with two of the four, as it won Best Original Score, and Phoenix won the Best Performance award, following in the footsteps of Heath Ledger, who won a Golden Globe for his portrayal of Joker in The Dark Knight. The two awards mean it has set a record for comic book movies at the Golden Globes by winning two awards in a single night, more than any other comic book movie."
    },
    {
        imageUrl: "../../assets/newsPictures/ironmanNews.jpg",
        title: "Iron Man: Robert Downey Jr. Meets Young Fan Whose Life Was Changed By Marvel Hero",
        shortDesc: "While guest hosting The Ellen DeGeneres Show, Robert Downey Jr. met a young fan who claims the Iron Man star changed his life. Downey...",
        longDesc: "While guest hosting The Ellen DeGeneres Show, Robert Downey Jr. met a young fan who claims the Iron Man star changed his life. Downey Jr. filled in for DeGeneres on a show this week. Downey Jr. and DeGeneres have bonded since she first interviewed him on her show over 15 years ago. She has had him on several times since to promote his Iron Man movies and upcoming film Dolittle. This is the first time he appeared on the show solo as host. Other clips from the show revealed that he'd be interviewing Rami Malek, inviting The Black Eyed Peas to perform their hit single RITMO, and playing games like with the audience. The first Iron Man came to theaters in 2008 and is based on the comic book series of the same name. CEO and scientist Tony Stark is living life large, thriving off the fortune of Stark Industries until he is shot down by a missile and captured in Afghanistan. With only an electromagnet preventing the shrapnel from the missile going into his heart, he works alongside fellow prisoner Yo Hinsen to build a suit of armor powered by the electromagnet and escape from imprisonment. Upon returning home, Stark perfects the suit to become the superhuman Iron Man. Ellen Tube uploaded a video of Downey Jr. interviewing 10-year-old Vincent and his parents. Vincent's mother explained that Vincent stopped talking at the age of 1 and was diagnosed with autism at 4. When Downey Jr. asked what it was like to lose the ability to communicate, Vincent responded, painful. Vincent's father explained that it was difficult for Vincent to make friends and express his needs. Vincent then proudly declared that he his parents bought him an Iron Man helmet. Once he put the helmet on, he was able to talk through it, using his imagination to channel Iron Man and become a more confident version of himself."
    },
    {
        imageUrl: "../../assets/newsPictures/thanosNews.jpg",
        title: "Thanos Almost Had A Battle Axe Instead Of Weird Sword in Avengers: Endgame",
        shortDesc: "Thanos almost wielded a battle axe instead of a weird, giant sword in Avengers: Endgame, according to some recently...",
        longDesc: "Thanos almost wielded a battle axe instead of a weird, giant sword in Avengers: Endgame, according to some recently released concept art images. The arrival and subsequent battle with Thanos, the long-awaited Mad Titan of the Marvel Cinematic Universe, had been hinted at slowly among the many superhero films which took place before Avengers: Infinity War, with the villain's desire to obtain the titular infinity stones a driving force behind many of the previous movies' plots. Although he was eventually defeated two separate times in Avengers: Endgame, Thanos still remains one of the toughest enemies the Avengers have ever faced, with his eventual demise requiring the might of all of Earth's heroes combined. The final battle of Avengers: Endgame saw Thanos facing off against multiple Avengers at once, defending himself and delivering bone-shattering blows with a weird, double-bladed sword. Now, fans know the strange weapon wasn't the only one the filmmakers considered. According to Ian Joyner, a concept artist who has worked on multiple Marvel projects in the past including Avengers: Endgame and Avengers: Infinity War, one of Thanos' earlier designs originally had him equipped with a large battle axe instead of that weird anime-sized sword. Thanos was often shown with battle armor or a helmet on during his various short cameos in the films leading up to Avengers: Infinity War, but his largest role saw the villain's head mostly uncovered, and that movie ended with him sitting alone with nothing on but a dirty t-shirt and pair of pants. However, thanks to the time-traveling shenanigans of Avengers: Endgame, the past version of Thanos was re-introduced to the heroes, and this version was the battle-ready, not yet exhausted Thanos dressed in his full armor. In the film, Thanos wields a large, double-bladed sword which was powerful enough to stop attacks from Thor's axe and strong enough to chip away at Captain America's shield."
    },
    {
        imageUrl: "../../assets/newsPictures/onceuponatimeNews.jpg",
        title: "10 Things About The Making Of Once Upon A Time In Hollywood That You Never Knew",
        shortDesc: "One of the most exciting films of 2019 was Quentin Tarantino's Once Upon a Time… in Hollywood. Tarantino's films always...",
        longDesc: "One of the most exciting films of 2019 was Quentin Tarantino's Once Upon a Time… in Hollywood. Tarantino's films always draw a lot of attention but this particular story, set in 1960's Hollywood and starring Leonardo DiCaprio and Brad Pitt was especially enticing. The film proved to be a big hit at the box office as well as a critical success, being named by many as one of the best movies of the year and even getting nominated for an Oscar for Best Picture. The movie is a wonderful look at Hollywood at the time and the making of the film makes for an interesting Hollywood story as well. Here are some things you might not have known about the making of Once Upon a Time…in Hollywood. Tarantino is known for taking his time with his film scripts, working on ideas for years, even decades. While this particular script was not his longest development, it did still have an interesting path to getting made. Initially, Tarantino envisioned the story about a Hollywood actor and his stuntman as a novel. However, as the story continued to expand, he realized it was more suitable for a film. Still, not wanting any leaks like his previous film The Hateful Eight, Tarantino would leave the ending out of the script when showing it to some people. Tarantino has called this script his most personal yet and refers to it as a memory piece. He grew up in Los Angeles and spent a lot of time in the areas that are shown in the film. He also talked about the strong memories he had of driving around Hollywood with his stepfather and wanting to recreate that feeling in the movie. Tarantino also snuck in a fun personal nod late in the film. When Sharon Tate makes mention of the premiere happening at a nearby porno theater, the theater in question is Eros Theater which was later changed into a theater called the New Beverley which is owned by Tarantino."
    }
]